spring:
  dataSource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: scott
    password: 12341
    driver-class-name: oracle.jdbc.driver.OracleDriver
    tomcat:
      initial-size: 10
      max-wait: 10000
      max-active: 50
      max-idle: 10
      min-idle: 10
      test-on-borrow: true

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/sql/*.xml